stages:
  - build
  - deploy

jupyter-build:
  stage: build
  image: python:3.11
  before_script:
    - pip install poetry
    - poetry install
    - source `poetry env info --path`/bin/activate  
  script:
    - jupyter-book clean manual
    - jupyter-book build manual
  artifacts:
    paths:
      - manual/_build/

pages:
  stage: deploy
  image: busybox:latest
  script:
    - mv _build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
