[tool.poetry]
name = "affinis"
version = "0.1.0"
description = ""
authors = ["tbsexton <tbsexton@asu.edu>"]

[tool.poetry.dependencies]
python = "^3.7"
jax = "^0.2.4"
pandas = "^1.1.3"
networkx = "^2.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
