[tool.poetry]
name = "affinis"
version = "0.2.1"
description = ""
authors = ["Rachael Sexton <rtbs@nist.gov>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pandas = "^1.1.3"
networkx = "^2.5"
scikit-learn = "^1.2.0"
toolz = "^0.12.0"
statsmodels = "^0.13.5"
intervaltree = "^3.1.0"
bidict = "^0.22.1"
scipy = "^1.10"

[tool.poetry.group.dev.dependencies]
pytest = "^5.2"
ipykernel = "^6.9.2"
seaborn = "^0.12.1"
black = "^23.3.0"
ruff = "^0.0.275"


[tool.poetry.group.docs.dependencies]
pydlc = "^0.2"
pygraphviz = "^1.11"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
